ref: /home/users/xi/Waterbuck_project/Reference/DefassaWaterbuck.fasta
outmain: results
tmp_dir: /brendaData/xi/tmp
settings: #### for k, check multiple qc from QC results to see the reads length distribution
 k: 150
 e: 2
 m: 1
